name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v17

      - uses: DeterminateSystems/magic-nix-cache-action@v9

      - name: Flake check
        run: nix flake check --no-build

      - name: Evaluate package
        run: nix eval .#packages.x86_64-linux.aws-sam-cli
